# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_association.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='file_association.proto',
  package='asgard',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x66ile_association.proto\x12\x06\x61sgard\"3\n\x0f\x46ileAssociation\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x12\n\nextensions\x18\x02 \x01(\tb\x06proto3'
)




_FILEASSOCIATION = _descriptor.Descriptor(
  name='FileAssociation',
  full_name='asgard.FileAssociation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='asgard.FileAssociation.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extensions', full_name='asgard.FileAssociation.extensions', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['FileAssociation'] = _FILEASSOCIATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileAssociation = _reflection.GeneratedProtocolMessageType('FileAssociation', (_message.Message,), {
  'DESCRIPTOR' : _FILEASSOCIATION,
  '__module__' : 'file_association_pb2'
  # @@protoc_insertion_point(class_scope:asgard.FileAssociation)
  })
_sym_db.RegisterMessage(FileAssociation)


# @@protoc_insertion_point(module_scope)
