# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: software.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import file_pb2 as file__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='software.proto',
  package='asgard',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0esoftware.proto\x12\x06\x61sgard\x1a\nfile.proto\"\x86\x02\n\x08Software\x12\x1a\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x0c.asgard.File\x12\x13\n\x0b\x63ommon_name\x18\x02 \x01(\t\x12\x10\n\x08homepage\x18\x03 \x01(\t\x12\x12\n\ngit_commit\x18\x04 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x0f\n\x07version\x18\x07 \x01(\t\x12\x15\n\rversion_count\x18\x08 \x01(\r\x12)\n\x0csupported_os\x18\t \x03(\x0e\x32\x13.asgard.SupportedOS\x12+\n\raddress_space\x18\n \x01(\x0e\x32\x14.asgard.AddressSpace*~\n\x0bSupportedOS\x12\r\n\tWINDOWS10\x10\x00\x12\r\n\tWINDOWS11\x10\x01\x12\x0f\n\x0bMACOS_INTEL\x10\x02\x12\x11\n\rMACOS_SILICON\x10\x03\x12\n\n\x06UBUNTU\x10\x04\x12\n\n\x06\x46\x45\x44ORA\x10\x05\x12\x08\n\x04\x41RCH\x10\x06\x12\x0b\n\x07SOLARIS\x10\x07*&\n\x0c\x41\x64\x64ressSpace\x12\n\n\x06\x42IT_32\x10\x00\x12\n\n\x06\x42IT_64\x10\x01\x62\x06proto3'
  ,
  dependencies=[file__pb2.DESCRIPTOR,])

_SUPPORTEDOS = _descriptor.EnumDescriptor(
  name='SupportedOS',
  full_name='asgard.SupportedOS',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WINDOWS10', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WINDOWS11', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MACOS_INTEL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MACOS_SILICON', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UBUNTU', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FEDORA', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ARCH', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SOLARIS', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=303,
  serialized_end=429,
)
_sym_db.RegisterEnumDescriptor(_SUPPORTEDOS)

SupportedOS = enum_type_wrapper.EnumTypeWrapper(_SUPPORTEDOS)
_ADDRESSSPACE = _descriptor.EnumDescriptor(
  name='AddressSpace',
  full_name='asgard.AddressSpace',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BIT_32', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BIT_64', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=431,
  serialized_end=469,
)
_sym_db.RegisterEnumDescriptor(_ADDRESSSPACE)

AddressSpace = enum_type_wrapper.EnumTypeWrapper(_ADDRESSSPACE)
WINDOWS10 = 0
WINDOWS11 = 1
MACOS_INTEL = 2
MACOS_SILICON = 3
UBUNTU = 4
FEDORA = 5
ARCH = 6
SOLARIS = 7
BIT_32 = 0
BIT_64 = 1



_SOFTWARE = _descriptor.Descriptor(
  name='Software',
  full_name='asgard.Software',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='asgard.Software.file', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='common_name', full_name='asgard.Software.common_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='homepage', full_name='asgard.Software.homepage', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='git_commit', full_name='asgard.Software.git_commit', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author', full_name='asgard.Software.author', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='asgard.Software.description', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='asgard.Software.version', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version_count', full_name='asgard.Software.version_count', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='supported_os', full_name='asgard.Software.supported_os', index=8,
      number=9, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address_space', full_name='asgard.Software.address_space', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=301,
)

_SOFTWARE.fields_by_name['file'].message_type = file__pb2._FILE
_SOFTWARE.fields_by_name['supported_os'].enum_type = _SUPPORTEDOS
_SOFTWARE.fields_by_name['address_space'].enum_type = _ADDRESSSPACE
DESCRIPTOR.message_types_by_name['Software'] = _SOFTWARE
DESCRIPTOR.enum_types_by_name['SupportedOS'] = _SUPPORTEDOS
DESCRIPTOR.enum_types_by_name['AddressSpace'] = _ADDRESSSPACE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Software = _reflection.GeneratedProtocolMessageType('Software', (_message.Message,), {
  'DESCRIPTOR' : _SOFTWARE,
  '__module__' : 'software_pb2'
  # @@protoc_insertion_point(class_scope:asgard.Software)
  })
_sym_db.RegisterMessage(Software)


# @@protoc_insertion_point(module_scope)
