# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tv.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import file_pb2 as file__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tv.proto',
  package='asgard',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08tv.proto\x12\x06\x61sgard\x1a\nfile.proto\"\x8b\x01\n\x06Season\x12\x1a\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x0c.asgard.File\x12\x15\n\rseason_number\x18\x02 \x01(\r\x12\x15\n\repisode_count\x18\x03 \x01(\r\x12\x14\n\x0cseason_title\x18\x04 \x01(\r\x12!\n\x08\x65pisodes\x18\x05 \x03(\x0b\x32\x0f.asgard.Episode\"=\n\x07\x45pisode\x12\x1a\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x0c.asgard.File\x12\x16\n\x0e\x65pisode_number\x18\x02 \x01(\r\"t\n\x08TVSeries\x12\x1a\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x0c.asgard.File\x12\x14\n\x0cseason_count\x18\x02 \x01(\x05\x12\x15\n\repisode_count\x18\x03 \x01(\r\x12\x1f\n\x07seasons\x18\x04 \x03(\x0b\x32\x0e.asgard.Seasonb\x06proto3'
  ,
  dependencies=[file__pb2.DESCRIPTOR,])




_SEASON = _descriptor.Descriptor(
  name='Season',
  full_name='asgard.Season',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='asgard.Season.file', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='season_number', full_name='asgard.Season.season_number', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='episode_count', full_name='asgard.Season.episode_count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='season_title', full_name='asgard.Season.season_title', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='episodes', full_name='asgard.Season.episodes', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=172,
)


_EPISODE = _descriptor.Descriptor(
  name='Episode',
  full_name='asgard.Episode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='asgard.Episode.file', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='episode_number', full_name='asgard.Episode.episode_number', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=235,
)


_TVSERIES = _descriptor.Descriptor(
  name='TVSeries',
  full_name='asgard.TVSeries',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='asgard.TVSeries.file', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='season_count', full_name='asgard.TVSeries.season_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='episode_count', full_name='asgard.TVSeries.episode_count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seasons', full_name='asgard.TVSeries.seasons', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=353,
)

_SEASON.fields_by_name['file'].message_type = file__pb2._FILE
_SEASON.fields_by_name['episodes'].message_type = _EPISODE
_EPISODE.fields_by_name['file'].message_type = file__pb2._FILE
_TVSERIES.fields_by_name['file'].message_type = file__pb2._FILE
_TVSERIES.fields_by_name['seasons'].message_type = _SEASON
DESCRIPTOR.message_types_by_name['Season'] = _SEASON
DESCRIPTOR.message_types_by_name['Episode'] = _EPISODE
DESCRIPTOR.message_types_by_name['TVSeries'] = _TVSERIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Season = _reflection.GeneratedProtocolMessageType('Season', (_message.Message,), {
  'DESCRIPTOR' : _SEASON,
  '__module__' : 'tv_pb2'
  # @@protoc_insertion_point(class_scope:asgard.Season)
  })
_sym_db.RegisterMessage(Season)

Episode = _reflection.GeneratedProtocolMessageType('Episode', (_message.Message,), {
  'DESCRIPTOR' : _EPISODE,
  '__module__' : 'tv_pb2'
  # @@protoc_insertion_point(class_scope:asgard.Episode)
  })
_sym_db.RegisterMessage(Episode)

TVSeries = _reflection.GeneratedProtocolMessageType('TVSeries', (_message.Message,), {
  'DESCRIPTOR' : _TVSERIES,
  '__module__' : 'tv_pb2'
  # @@protoc_insertion_point(class_scope:asgard.TVSeries)
  })
_sym_db.RegisterMessage(TVSeries)


# @@protoc_insertion_point(module_scope)
